### ISSUE TITLE
Error: Failure to display accurately files that correlate with the input in the search bar

### ISSUE THREAD

**Issue by Sriramgireesh** [jaspwr/glimpse#9]
The following example will illustrate the problem. I am trying to search for "The Trade Unions Act 1926.pdf". When I type "trade", I can find the relevant file after scrolling down. 

![image](https://github.com/user-attachments/assets/efec738c-7bb9-4cb9-a18c-8faf839aebac)

However, when I type "trade union" or "trade unions" or "trade 1926", the file fails to appear in the search results: 
![image](https://github.com/user-attachments/assets/be7cab04-93db-4882-b075-d188893d09b5)

**Comment by jaspwr** [comment]
Thank you for pointing this out. I will try and improve this.

**Comment by jaspwr** [comment]
I think I've fixed this. Will test a little more.
![image](https://github.com/user-attachments/assets/ff5cfdbb-e2fb-4ea0-bcfd-85c78e7dfba5)
